[env]
TERM = "xterm-256color"

[shell]
program = "/bin/fish"
args = ["-l", "-c", "tmux new -A -s katti"]

[window]
dynamic_padding = true
padding = { x = 10, y = 10 }

[font]
normal = { family = "ComicShannsMono Nerd Font", style = "Regular" }
size = 13

[colors.bright]
black = "#686868"
red = "#ff5c57"
green = "#5af78e"
yellow = "#f3f99d"
blue = "#57c7ff"
magenta = "#ff6ac1"
cyan = "#9aedfe"
white = "#eff0eb"

[colors.normal]
black = "#282a36"
red = "#ff5c57"
green = "#5af78e"
yellow = "#f3f99d"
blue = "#57c7ff"
magenta = "#ff6ac1"
cyan = "#9aedfe"
white = "#f1f1f0"

[colors.primary]
background = "#282a36"
foreground = "#eff0eb"

[colors.footer_bar]
background = "#282a36"
foreground = "#eff0eb"

[colors.search.matches]
background = "#ff5c57"
foreground = "CellBackground"

[colors.cursor]
cursor = "#97979b"

[colors.selection]
text = "#282a36"
background = "#feffff"
